version: "3.9"
services:

  kafka:
    image: apache/kafka:3.7.1
    ports:
      - "9092:9092"

  user-service:
    image: userimage
    ports:
      - "4000:4000"
    volumes:
      - ./user-service:/app
    environment:
      - KAFKA_BROKER
      - MONGO_URI
      - JWT_SECRET

    depends_on:
      - kafka

  product-service:
    image: productimage
    ports:
      - "4001:4001"
    
    volumes:
      - ./product-service:/app
    
    environment:
      - KAFKA_BROKER
      - MONGO_URI

    depends_on:
      - kafka

  order-service:
    image: orderimage
    ports:
      - "4002:4002"

    volumes:
      - ./order-service:/app
    environment:
      - KAFKA_BROKER
      - MONGO_URI

    depends_on:
      - kafka