version: "3.9"
services:

  zookeeper:
    image: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper

  user-service:
    image: userimage
    ports:
      - "4000:4000"
    volumes:
      - ./user-service:/app
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI
      - JWT_SECRET=your_jwt_secret

    depends_on:
      - kafka

  product-service:
    image: productimage
    ports:
      - "4001:4001"
    
    volumes:
      - ./product-service:/app
    
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI

    depends_on:
      - kafka

  order-service:
    image: orderimage
    ports:
      - "4002:4002"

    volumes:
      - ./order-service:/app
    environment:
      - KAFKA_BROKER=kafka:9092
      - MONGO_URI

    depends_on:
      - kafka

  api-gateway-service:
    image: gateway
    ports:
      - "3000:3000"

    depends_on:
      - user-service
      - product-service
      - order-service